version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-volume-demo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example123
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Volume gắn vào thư mục lưu dữ liệu trong container

volumes:
  mysql_data:
