version: '3'
services:
  node-app:
    build: .
    container_name: node_container
    ports:
      - "3000:3000"
    volumes: 
      - .:/app
    environment:
      - NODE_ENV=production
    restart: always
